### ISSUE TITLE
Pug-lint doesn´t work in Atom

### ISSUE THREAD

**Issue by inmagination** [AtomLinter/atom-linter-pug#18]
I installed the plugin in atom and throws an error: Pug-lint config not found.
Please help!!!!

**Comment by johnjcamilleri** [comment]
Well, you need to provide your own config file for your project. Here's an example: https://github.com/clocklimited/pug-lint-config-clock/blob/master/.pug-lintrc.json

But I agree that this plugin should come with a default linter configuration file!

**Comment by Arcanemagus** [comment]
@johnjcamilleri That's an issue better taken up with `pug-lint` itself. Other linters (eg. ESlint, stylelint) that support configurations will check basic syntax with no configuration, only enabling semantic checks when provided with a configuration. From what you are saying it sounds like `pug-lint` simply does nothing without a configuration which is a bit silly on their part.

**Comment by Arcanemagus** [comment]
I _believe_ this was fixed in #16, released in v2.0.0. If you are still having issues @inmagination feel free to re-open this.
