### ISSUE TITLE
atom-linter-pug does not recognize a config file with "extends" in it

### ISSUE THREAD

**Issue by Pustur** [AtomLinter/atom-linter-pug#8]
I tried this plugin with a full config file (with all the rules inside) and it worked fine.

However if i try to extract the rules in a new npm package and i update the config file to include only the `extends` keyword like this:

```
{
  "extends": "pustur"
}
```

It doesn't work anymore.

---

If i run the linter in the command line (with `npm test`) everything works as expected (so the external configuration works there).
But inside atom it seems like it doesn't recognize the config file **if it contains the `extends` keyword**

Is this a bug or am i doing something wrong?
Thanks in advance.

---

**Atom:** 1.10.2
**linter-pug:** 1.3.0
my custom config file can be found here: [pug-lint-config-pustur](https://github.com/Pustur/pug-lint-config-pustur)

**Comment by lindekaer** [comment]
I have the same issue. I have added the "pugLintConfig" in my package.json, but it is not recognized

**Comment by Arcanemagus** [comment]
This is rather interesting, as we are directly calling the code from `pug-lint` that finds the configuration [here](https://github.com/AtomLinter/atom-linter-pug/blob/v1.3.0/lib/init.coffee#L37), so I'm not sure how this is breaking. @matthojo any ideas here?

**Comment by matthojo** [comment]
Looks like support for extends was introduced to in Pug-lint `v2.2.0` and we're currently on `v2.1.9`. With the most recent version of Pug-lint being `v2.3.0`. I imagine updating the `package.json` version reference will help users who have `v2.1.9` installed.

**Comment by Arcanemagus** [comment]
Ah ha! Should we pin `pug-lint` and let Greenkeeper send in a PR for each new version? That's what most of the other linters that bundle a Node.js linter do so updates like this don't get missed. If not pinning maybe move to `~2.3.0` so we get a notification for enhancement releases?

**Comment by matthojo** [comment]
I think that would make most sense. I don't use this linter anymore so
future updates are best automated as possible.
